# Generated by Django 3.2 on 2021-08-26 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='contact',
            field=models.CharField(max_length=15),
        ),
    ]
