# Generated by Django 3.2 on 2021-08-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_note_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='uploadingdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
