# Generated by Django 3.2 on 2021-08-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_note_uploadingdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='filetype',
            field=models.CharField(choices=[('pdf', 'pdf'), ('txt', 'txt'), ('docs', 'docs'), ('jpeg', 'jpeg'), ('png', 'png')], max_length=50),
        ),
        migrations.AlterField(
            model_name='note',
            name='notesfile',
            field=models.FileField(upload_to='Notes'),
        ),
        migrations.AlterField(
            model_name='note',
            name='uploadingdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
