# Generated by Django 3.2 on 2021-08-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20210829_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='branch',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ME', 'ME'), ('EE', 'EE'), ('CE', 'CE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='status',
            field=models.CharField(default='Pending', max_length=15),
        ),
    ]
