# Generated by Django 3.2 on 2021-09-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_signup_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='photo',
            field=models.ImageField(blank=True, default='media/Profile/R.png', null=True, upload_to='profile'),
        ),
    ]
