# Generated by Django 3.2 on 2021-09-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_signup_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='photo',
            field=models.ImageField(default='Profile/R.png', upload_to='profile'),
        ),
    ]
